Implemented the feature of validating the user's configuration
booster-labs/rocket-booster pull request #115
Opened 2021-07-09 02:52 UTC by lorenzoc25

2021-07-17 07:25 UTC, xiaoyang-sde requested changes

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +    // security,
I think these comments could be removed

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +    throw new Error('Invalid upstream configuration. Please check again that you did not input empty value.');
May change to `The required field 'upstream' in the configuration is missing`.

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +        throw new Error('Invalid domain configuration. Please check that you included domain in the configuration');
The required field 'domain' in the `upstream` configuration is missing.

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +    upstream.forEach((userConfig) => {
`userConfig` -> `upstreamOptions`

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +  const checkFirewall = (userConfig: FirewallOptions) : void => {
This function could be moved outside of `useValidate`. The parameters should be placed in a new line. Please use an informative name for the function such as `validateFirewallOptions`.
```
const validateFirewallOptions = (
  firewallOptions: FirewallOptions,
): void =>
```

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +  const checkError = (userConfig : ErrorOptions) : void => {
This function could be moved outside of `useValidate`.

2021-07-17 07:25 UTC, xiaoyang-sde commented on src/validate.ts
> +      throw new Error('Invalid customized error configuration. ');
```suggestion
      throw new Error('Invalid customized error configuration.');
```

2021-07-17 07:27 UTC, xiaoyang-sde commented
The unit test could be removed if it's not easy to implement.

2021-07-17 19:47 UTC, lorenzoc25 commented
Thanks for the suggesting! I've removed the test cases and re-format the file in the newest commit :)

2021-07-18 01:09 UTC, xiaoyang-sde approved these changes

2021-07-18 01:09 UTC, merged