Implemented Load balancing based on client’s IP
booster-labs/rocket-booster pull request #129
Opened 2021-07-20 17:57 UTC by lorenzoc25

2021-07-21 00:01 UTC, xiaoyang-sde requested changes
Thanks for your contribution! I think we could add a fallback option to select a random upstream if the IP address is missing.

2021-07-21 00:01 UTC, xiaoyang-sde commented on src/load-balancing.ts
> +  return ip.split('0').map((octect, index, array) => parseInt(octect, 10) * (256 ** (array.length - index - 1))).reduce((accumulator, current) => accumulator + current);
I don't think this function is correct...

2021-07-21 00:25 UTC, lorenzoc25 commented on src/load-balancing.ts
> +  return ip.split('0').map((octect, index, array) => parseInt(octect, 10) * (256 ** (array.length - index - 1))).reduce((accumulator, current) => accumulator + current);
that was a careless mistake... sorry for that. I've fixed that in the newer version

2021-07-23 08:50 UTC, xiaoyang-sde commented on src/load-balancing.ts
> +  }
I think you've already checked if `ip` is null in line 20.

2021-07-24 16:25 UTC, xiaoyang-sde approved these changes

2021-07-24 16:26 UTC, merged